---
- name: Create new post
  hosts: localhost
  gather_facts: yes
  connection: ssh
  tasks:
    - include_role:
        name: packages
        tasks_from: install

    - include_role:
        name: nginx
        tasks_from: configure

    - include_role:
        name: cron
        tasks_from: schedule
