- name: "build {{ envi }}"
  shell: bundle exec jekyll build -d {0} build /var/www/myexam.{{ envi }}/html
  args:
    executable: /bin/bash
    chdir: "{{ playbook_dir }}"
  register: build_envi_out
  notify:
    - restart nginx
  tags:
    - always

- name: build_envi_out
  debug:
    msg: "{{ build_envi_out }}"
  tags:
    - always
