# TEMP develop to master
- name: commit code
  shell: |
    /usr/bin/git remote set-url origin git@github.com:lovenfrancist/lovenfrancist.github.io.git
    eval $(ssh-agent -s) && ssh-add ~/.ssh/id_rsa

    /usr/bin/git add -A
    /usr/bin/git commit -m 'New Post - {{ ansible_date_time.date }}'
    /usr/bin/git push origin develop:develop
  register: commit_code_out
  tags:
    - commit

- name: commit_code_out
  debug:
    msg: "{{ commit_code_out }}"
  tags:
    - commit

- name: Get current version
  include_vars:
    file: "{{ playbook_dir }}/_config.yml"
  tags:
    - commit

- name: Initialize current_version variable
  set_fact:
    current_version: "{{ description.split(':')[1].strip() }}"
  tags:
    - commit

- name: create tag
  shell: |
    /usr/bin/git tag -a v{{ current_version }} -m, 'v{{ current_version }}'
    /usr/bin/git push origin v{{ current_version }}
  register: create_tag_out
  when: envi == "staging"
  tags:
    - commit

- name: create_tag_out
  debug:
    msg: "{{ create_tag_out }}"
  tags:
    - commit
