# dev
# */10 * * * * (cd ~/lovenfrancist.github.io && exec python my_exam.py dev)

# staging
# 0 * * * * (cd ~/lovenfrancist.github.io && exec python my_exam.py staging)

# poll
# */5 * * * * (cd ~/lovenfrancist.github.io && exec ./poll_github.sh)
