# - name: ensure dev script runs every 10 mins
#   cron:
#     name: "run script for DEV"
#     minute: "*/10"
#     job: "(cd {{ playbook_dir }} && exec python my_exam.py dev)"

- name: ensure dev playbook runs every 10 mins
  cron:
    name: "run playbook for DEV"
    minute: "*/10"
    job: "(cd {{ playbook_dir }} && exec ansible-playbook my_exam_playbook.yaml --tags 'commit' --extra-vars 'env=dev')"

# - name: ensure staging script runs every hour
#   cron:
#     name: "run script for STAGING"
#     minute: "*/60"
#     job: "(cd {{ playbook_dir }} && exec python my_exam.py staging)"

- name: ensure staging playbook runs every hour
  cron:
    name: "run playbook for STAGING"
    minute: "*/60"
    job: "(cd {{ playbook_dir }} && exec ansible-playbook my_exam_playbook.yaml --tags 'commit' --extra-vars 'env=staging')"

- name: ensure polling script runs every 5 mins
  cron:
    name: "run script for polling"
    minute: "*/5"
    job: "{{ playbook_dir }}/poll_github.sh"
